export function createAppState() {
  return {
    canvasW: 64,
    canvasH: 64,
    zoomFactor: 8,
    currentFrame: 0,
    wasmReady: false,
    dirty: true,
    modifiedSinceSave: false,
    rafPending: false,
    pixelBuf: null,
    imageData: null,
    selectedLayer: 0,
    prefAspectLock: false,
    prefAspectRatio: 1,
    builtinTextureLoadPromise: null,
    projectBaseName: "project",
    detachedPreviewWindow: null,
    detachedPreviewTimer: null,
    detachedPreviewPlaying: false,
    detachedPreviewFrame: 0,
    detachedPreviewDir: 1,
    layerPreviewToken: 0,
    layerPreviewRevision: 1,
    layerPreviewCache: new Map(),
    selectedCurve: 1,
    curveCanvas: null,
    curveCtx: null,
    curveDragPoint: -1,
    curveSelectedPoint: -1,
    shapeMode: "L",
    shapeCanvas: null,
    shapeCtx: null,
    shapeCommands: [],
    shapeDragHandle: null,
    shapeSelectedHandle: null,
    recentHandlesDbPromise: null,
    lastRenderMs: 0,
  };
}

export const LAYER_PREVIEW_SIZE = 36;
export const CURVE_POINT_LIMIT = 12;

export const BUILTIN_TEXTURE_FILES = [
  "Aura.jpg",
  "Checkers.bmp",
  "Circle.jpg",
  "Coal.jpg",
  "Fabric.bmp",
  "Hairline.bmp",
  "HairlineV.bmp",
  "Hexagon.png",
  "Magma.bmp",
  "Mosaic.bmp",
  "Plant.png",
  "Plasma.bmp",
  "PunchingMetal.png",
  "Radiation.jpg",
  "Sand.bmp",
  "Scratch.jpg",
  "Stripe.bmp",
  "StripeV.bmp",
];

export const SAMPLE_PROJECT_FILES = [
  "2Color_Pointed.knob",
  "3p_wedge.knob",
  "Aqua.knob",
  "Black_Gear.knob",
  "BlueDot_V.knob",
  "Blue_HSW.knob",
  "Blue_HSW2.knob",
  "CheckBox.knob",
  "ColorRing.knob",
  "CorkBoard.knob",
  "FabricStar.knob",
  "Granite.knob",
  "Gray_Ring2.knob",
  "GreenAb.knob",
  "Green_Radar.knob",
  "Green_VSW.knob",
  "LineShadow.knob",
  "Monotone_Simple.knob",
  "Number.knob",
  "Number_HSwitch.knob",
  "NumberedTick.knob",
  "Orange_Lever.knob",
  "Orange_Round.knob",
  "Pop_Meter.knob",
  "Red_Gear.knob",
  "Shape_sample.knob",
  "Small_Gaged.knob",
  "Ticked_HSlider.knob",
  "Waveform.knob",
  "White_Dip.knob",
  "White_Pan.knob",
  "White_Vol.knob",
  "White_Wave.knob",
  "Wood_Gear.knob",
  "face.knob",
  "g200kglogo.knob",
  "led.knob",
  "vu3.knob",
];

export const SESSION_KEY = "knobman_session_v2";
export const LEGACY_SESSION_KEY = "knobman_session";
export const RECENT_DOCS_KEY = "knobman_recent_docs_v1";
export const RECENT_DOC_LIMIT = 8;
export const HANDLE_DB_NAME = "knobman_recent_handles";
export const HANDLE_STORE_NAME = "handles";
export const WELCOME_SUPPRESS_KEY = "knobman_welcome_suppress";

export const PRIM_TYPES = [
  { value: 0, label: "None" },
  { value: 1, label: "Image" },
  { value: 2, label: "Circle" },
  { value: 3, label: "CircleFill" },
  { value: 4, label: "MetalCircle" },
  { value: 5, label: "WaveCircle" },
  { value: 6, label: "Sphere" },
  { value: 7, label: "Rect" },
  { value: 8, label: "RectFill" },
  { value: 9, label: "Triangle" },
  { value: 10, label: "Line" },
  { value: 11, label: "RadiateLine" },
  { value: 12, label: "H-Lines" },
  { value: 13, label: "V-Lines" },
  { value: 14, label: "Text" },
  { value: 15, label: "Shape" },
];

export const PARAM_DEFS = {
  name: { label: "Layer Name", type: "text" },
  primType: {
    label: "Primitive",
    type: "select",
    numeric: "int",
    options: PRIM_TYPES,
  },
  color: { label: "Color", type: "color" },
  file: { label: "Image Name", type: "text" },
  embeddedImage: { label: "Image File", type: "file", accept: "image/*" },
  text: { label: "Text", type: "text" },
  shape: { label: "Shape", type: "textarea" },
  fill: { label: "Fill", type: "checkbox" },
  bold: { label: "Bold", type: "checkbox" },
  italic: { label: "Italic", type: "checkbox" },
  font: {
    label: "Font",
    type: "number",
    numeric: "int",
    min: 0,
    max: 64,
    step: 1,
  },
  textureFile: {
    label: "Texture Slot",
    type: "number",
    numeric: "int",
    min: 0,
    max: 64,
    step: 1,
  },
  textureName: { label: "Texture Name", type: "text" },
  width: {
    label: "Width",
    type: "number",
    numeric: "float",
    min: 0,
    max: 200,
    step: 0.1,
  },
  length: {
    label: "Length",
    type: "number",
    numeric: "float",
    min: 0,
    max: 200,
    step: 0.1,
  },
  aspect: {
    label: "Aspect",
    type: "number",
    numeric: "float",
    min: -200,
    max: 200,
    step: 0.1,
  },
  round: {
    label: "Round",
    type: "number",
    numeric: "float",
    min: -100,
    max: 100,
    step: 0.1,
  },
  step: {
    label: "Step",
    type: "number",
    numeric: "float",
    min: -360,
    max: 360,
    step: 0.1,
  },
  angleStep: {
    label: "Angle Step",
    type: "number",
    numeric: "float",
    min: -360,
    max: 360,
    step: 0.1,
  },
  emboss: {
    label: "Emboss",
    type: "number",
    numeric: "float",
    min: -100,
    max: 100,
    step: 0.1,
  },
  embossDiffuse: {
    label: "Emboss Diffuse",
    type: "number",
    numeric: "float",
    min: -100,
    max: 200,
    step: 0.1,
  },
  ambient: {
    label: "Ambient",
    type: "number",
    numeric: "float",
    min: 0,
    max: 100,
    step: 0.1,
  },
  lightDir: {
    label: "Light Dir",
    type: "number",
    numeric: "float",
    min: -360,
    max: 360,
    step: 0.1,
  },
  specular: {
    label: "Specular",
    type: "number",
    numeric: "float",
    min: 0,
    max: 200,
    step: 0.1,
  },
  specularWidth: {
    label: "Spec Width",
    type: "number",
    numeric: "float",
    min: 0,
    max: 200,
    step: 0.1,
  },
  textureDepth: {
    label: "Texture Depth",
    type: "number",
    numeric: "float",
    min: -100,
    max: 200,
    step: 0.1,
  },
  textureZoom: {
    label: "Texture Zoom",
    type: "number",
    numeric: "float",
    min: 1,
    max: 400,
    step: 0.1,
  },
  diffuse: {
    label: "Diffuse",
    type: "number",
    numeric: "float",
    min: -100,
    max: 200,
    step: 0.1,
  },
  fontSize: {
    label: "Font Size",
    type: "number",
    numeric: "float",
    min: 1,
    max: 300,
    step: 0.1,
  },
  textAlign: {
    label: "Text Align",
    type: "select",
    numeric: "int",
    options: [
      { value: 0, label: "Center" },
      { value: 1, label: "Left" },
      { value: 2, label: "Right" },
    ],
  },
  frameAlign: {
    label: "Frame Align",
    type: "select",
    numeric: "int",
    options: [
      { value: 0, label: "Vertical Strip" },
      { value: 1, label: "Horizontal Strip" },
      { value: 2, label: "Files" },
    ],
  },
  numFrame: {
    label: "Frames",
    type: "number",
    numeric: "int",
    min: 1,
    max: 256,
    step: 1,
  },
  autoFit: { label: "Auto Fit", type: "checkbox" },
  transparent: {
    label: "Transparent",
    type: "select",
    numeric: "int",
    options: [
      { value: 0, label: "File Alpha" },
      { value: 1, label: "Force Opaque" },
      { value: 2, label: "Color Key" },
    ],
  },
  intelliAlpha: {
    label: "IntelliAlpha",
    type: "number",
    numeric: "int",
    min: 0,
    max: 100,
    step: 1,
  },
};

export const PARAMS_BY_PRIM_TYPE = {
  0: [],
  1: [
    "embeddedImage",
    "file",
    "autoFit",
    "intelliAlpha",
    "numFrame",
    "frameAlign",
    "transparent",
  ],
  2: [
    "color",
    "width",
    "round",
    "diffuse",
    "emboss",
    "embossDiffuse",
    "ambient",
    "lightDir",
    "specular",
    "specularWidth",
    "textureDepth",
    "textureZoom",
    "textureFile",
  ],
  3: [
    "color",
    "aspect",
    "diffuse",
    "ambient",
    "lightDir",
    "specular",
    "specularWidth",
    "textureDepth",
    "textureZoom",
    "textureFile",
  ],
  4: [
    "color",
    "aspect",
    "diffuse",
    "ambient",
    "lightDir",
    "specular",
    "specularWidth",
    "textureDepth",
    "textureZoom",
    "textureFile",
  ],
  5: [
    "color",
    "width",
    "step",
    "length",
    "diffuse",
    "emboss",
    "embossDiffuse",
    "ambient",
    "lightDir",
    "specular",
    "specularWidth",
  ],
  6: ["color", "aspect", "diffuse", "step", "angleStep"],
  7: [
    "color",
    "width",
    "round",
    "length",
    "aspect",
    "diffuse",
    "emboss",
    "embossDiffuse",
    "ambient",
    "lightDir",
    "specular",
    "specularWidth",
  ],
  8: [
    "color",
    "round",
    "aspect",
    "diffuse",
    "emboss",
    "embossDiffuse",
    "ambient",
    "lightDir",
    "specular",
    "specularWidth",
    "textureDepth",
    "textureZoom",
    "textureFile",
  ],
  9: ["color", "width", "round", "length", "fill", "diffuse"],
  10: ["color", "width", "length", "lightDir"],
  11: ["color", "width", "length", "angleStep", "step"],
  12: ["color", "width", "step"],
  13: ["color", "width", "step"],
  14: [
    "color",
    "text",
    "font",
    "fontSize",
    "textAlign",
    "frameAlign",
    "bold",
    "italic",
  ],
  15: ["color", "shape", "fill", "round", "diffuse", "width"],
};

export const CURVE_OPTIONS = [
  { value: 0, label: "Off" },
  { value: 1, label: "Linear" },
  { value: 2, label: "Curve 1" },
  { value: 3, label: "Curve 2" },
  { value: 4, label: "Curve 3" },
  { value: 5, label: "Curve 4" },
  { value: 6, label: "Curve 5" },
  { value: 7, label: "Curve 6" },
  { value: 8, label: "Curve 7" },
  { value: 9, label: "Curve 8" },
];

export const EFFECT_DEFS = {
  antiAlias: { label: "AntiAlias", type: "checkbox" },
  unfold: { label: "Unfold", type: "checkbox" },
  animStep: {
    label: "AnimStep",
    type: "number",
    numeric: "int",
    min: 0,
    max: 1024,
    step: 1,
  },
  zoomXYSepa: { label: "Zoom XY Sepa", type: "checkbox" },
  zoomXF: {
    label: "Zoom X From",
    type: "number",
    numeric: "float",
    min: -500,
    max: 500,
    step: 0.1,
  },
  zoomXT: {
    label: "Zoom X To",
    type: "number",
    numeric: "float",
    min: -500,
    max: 500,
    step: 0.1,
  },
  zoomXAnim: {
    label: "Zoom X Curve",
    type: "select",
    numeric: "int",
    options: CURVE_OPTIONS,
  },
  zoomYF: {
    label: "Zoom Y From",
    type: "number",
    numeric: "float",
    min: -500,
    max: 500,
    step: 0.1,
  },
  zoomYT: {
    label: "Zoom Y To",
    type: "number",
    numeric: "float",
    min: -500,
    max: 500,
    step: 0.1,
  },
  zoomYAnim: {
    label: "Zoom Y Curve",
    type: "select",
    numeric: "int",
    options: CURVE_OPTIONS,
  },
  offXF: {
    label: "Offset X From",
    type: "number",
    numeric: "float",
    min: -500,
    max: 500,
    step: 0.1,
  },
  offXT: {
    label: "Offset X To",
    type: "number",
    numeric: "float",
    min: -500,
    max: 500,
    step: 0.1,
  },
  offXAnim: {
    label: "Offset X Curve",
    type: "select",
    numeric: "int",
    options: CURVE_OPTIONS,
  },
  offYF: {
    label: "Offset Y From",
    type: "number",
    numeric: "float",
    min: -500,
    max: 500,
    step: 0.1,
  },
  offYT: {
    label: "Offset Y To",
    type: "number",
    numeric: "float",
    min: -500,
    max: 500,
    step: 0.1,
  },
  offYAnim: {
    label: "Offset Y Curve",
    type: "select",
    numeric: "int",
    options: CURVE_OPTIONS,
  },
  keepDir: { label: "Keep Dir", type: "checkbox" },
  centerX: {
    label: "Center X",
    type: "number",
    numeric: "float",
    min: -500,
    max: 500,
    step: 0.1,
  },
  centerY: {
    label: "Center Y",
    type: "number",
    numeric: "float",
    min: -500,
    max: 500,
    step: 0.1,
  },
  angleF: {
    label: "Angle From",
    type: "number",
    numeric: "float",
    min: -3600,
    max: 3600,
    step: 0.1,
  },
  angleT: {
    label: "Angle To",
    type: "number",
    numeric: "float",
    min: -3600,
    max: 3600,
    step: 0.1,
  },
  angleAnim: {
    label: "Angle Curve",
    type: "select",
    numeric: "int",
    options: CURVE_OPTIONS,
  },
  alphaF: {
    label: "Alpha From",
    type: "number",
    numeric: "float",
    min: 0,
    max: 100,
    step: 0.1,
  },
  alphaT: {
    label: "Alpha To",
    type: "number",
    numeric: "float",
    min: 0,
    max: 100,
    step: 0.1,
  },
  alphaAnim: {
    label: "Alpha Curve",
    type: "select",
    numeric: "int",
    options: CURVE_OPTIONS,
  },
  brightF: {
    label: "Brightness From",
    type: "number",
    numeric: "float",
    min: -100,
    max: 100,
    step: 0.1,
  },
  brightT: {
    label: "Brightness To",
    type: "number",
    numeric: "float",
    min: -100,
    max: 100,
    step: 0.1,
  },
  brightAnim: {
    label: "Brightness Curve",
    type: "select",
    numeric: "int",
    options: CURVE_OPTIONS,
  },
  contrastF: {
    label: "Contrast From",
    type: "number",
    numeric: "float",
    min: -100,
    max: 100,
    step: 0.1,
  },
  contrastT: {
    label: "Contrast To",
    type: "number",
    numeric: "float",
    min: -100,
    max: 100,
    step: 0.1,
  },
  contrastAnim: {
    label: "Contrast Curve",
    type: "select",
    numeric: "int",
    options: CURVE_OPTIONS,
  },
  saturationF: {
    label: "Saturation From",
    type: "number",
    numeric: "float",
    min: -100,
    max: 100,
    step: 0.1,
  },
  saturationT: {
    label: "Saturation To",
    type: "number",
    numeric: "float",
    min: -100,
    max: 100,
    step: 0.1,
  },
  saturationAnim: {
    label: "Saturation Curve",
    type: "select",
    numeric: "int",
    options: CURVE_OPTIONS,
  },
  hueF: {
    label: "Hue From",
    type: "number",
    numeric: "float",
    min: -360,
    max: 360,
    step: 0.1,
  },
  hueT: {
    label: "Hue To",
    type: "number",
    numeric: "float",
    min: -360,
    max: 360,
    step: 0.1,
  },
  hueAnim: {
    label: "Hue Curve",
    type: "select",
    numeric: "int",
    options: CURVE_OPTIONS,
  },
  mask1Ena: { label: "Enable", type: "checkbox" },
  mask1Type: {
    label: "Type",
    type: "select",
    numeric: "int",
    options: [
      { value: 0, label: "Rotation" },
      { value: 1, label: "Radial" },
      { value: 2, label: "Horizontal" },
      { value: 3, label: "Vertical" },
    ],
  },
  mask1Grad: {
    label: "Gradation",
    type: "number",
    numeric: "float",
    min: 0,
    max: 100,
    step: 0.1,
  },
  mask1GradDir: {
    label: "Grad Dir",
    type: "number",
    numeric: "int",
    min: 0,
    max: 8,
    step: 1,
  },
  mask1StartF: {
    label: "Start From",
    type: "number",
    numeric: "float",
    min: -360,
    max: 360,
    step: 0.1,
  },
  mask1StartT: {
    label: "Start To",
    type: "number",
    numeric: "float",
    min: -360,
    max: 360,
    step: 0.1,
  },
  mask1StartAnim: {
    label: "Start Curve",
    type: "select",
    numeric: "int",
    options: CURVE_OPTIONS,
  },
  mask1StopF: {
    label: "Stop From",
    type: "number",
    numeric: "float",
    min: -360,
    max: 360,
    step: 0.1,
  },
  mask1StopT: {
    label: "Stop To",
    type: "number",
    numeric: "float",
    min: -360,
    max: 360,
    step: 0.1,
  },
  mask1StopAnim: {
    label: "Stop Curve",
    type: "select",
    numeric: "int",
    options: CURVE_OPTIONS,
  },
  mask2Ena: { label: "Enable", type: "checkbox" },
  mask2Op: {
    label: "Operation",
    type: "select",
    numeric: "int",
    options: [
      { value: 0, label: "AND" },
      { value: 1, label: "OR" },
    ],
  },
  mask2Type: {
    label: "Type",
    type: "select",
    numeric: "int",
    options: [
      { value: 0, label: "Rotation" },
      { value: 1, label: "Radial" },
      { value: 2, label: "Horizontal" },
      { value: 3, label: "Vertical" },
    ],
  },
  mask2Grad: {
    label: "Gradation",
    type: "number",
    numeric: "float",
    min: 0,
    max: 100,
    step: 0.1,
  },
  mask2GradDir: {
    label: "Grad Dir",
    type: "number",
    numeric: "int",
    min: 0,
    max: 8,
    step: 1,
  },
  mask2StartF: {
    label: "Start From",
    type: "number",
    numeric: "float",
    min: -360,
    max: 360,
    step: 0.1,
  },
  mask2StartT: {
    label: "Start To",
    type: "number",
    numeric: "float",
    min: -360,
    max: 360,
    step: 0.1,
  },
  mask2StartAnim: {
    label: "Start Curve",
    type: "select",
    numeric: "int",
    options: CURVE_OPTIONS,
  },
  mask2StopF: {
    label: "Stop From",
    type: "number",
    numeric: "float",
    min: -360,
    max: 360,
    step: 0.1,
  },
  mask2StopT: {
    label: "Stop To",
    type: "number",
    numeric: "float",
    min: -360,
    max: 360,
    step: 0.1,
  },
  mask2StopAnim: {
    label: "Stop Curve",
    type: "select",
    numeric: "int",
    options: CURVE_OPTIONS,
  },
  fMaskEna: {
    label: "Mode",
    type: "select",
    numeric: "int",
    options: [
      { value: 0, label: "Off" },
      { value: 1, label: "Range" },
      { value: 2, label: "Bitmask" },
    ],
  },
  fMaskStart: {
    label: "Range Start",
    type: "number",
    numeric: "float",
    min: 0,
    max: 100,
    step: 0.1,
  },
  fMaskStop: {
    label: "Range Stop",
    type: "number",
    numeric: "float",
    min: 0,
    max: 100,
    step: 0.1,
  },
  fMaskBits: { label: "Bitmask", type: "text" },
  sLightDirF: {
    label: "LightDir From",
    type: "number",
    numeric: "float",
    min: -360,
    max: 360,
    step: 0.1,
  },
  sLightDirT: {
    label: "LightDir To",
    type: "number",
    numeric: "float",
    min: -360,
    max: 360,
    step: 0.1,
  },
  sLightDirAnim: {
    label: "LightDir Curve",
    type: "select",
    numeric: "int",
    options: CURVE_OPTIONS,
  },
  sDensityF: {
    label: "Density From",
    type: "number",
    numeric: "float",
    min: 0,
    max: 100,
    step: 0.1,
  },
  sDensityT: {
    label: "Density To",
    type: "number",
    numeric: "float",
    min: 0,
    max: 100,
    step: 0.1,
  },
  sDensityAnim: {
    label: "Density Curve",
    type: "select",
    numeric: "int",
    options: CURVE_OPTIONS,
  },
  dLightDirEna: { label: "Enable", type: "checkbox" },
  dLightDirF: {
    label: "LightDir From",
    type: "number",
    numeric: "float",
    min: -360,
    max: 360,
    step: 0.1,
  },
  dLightDirT: {
    label: "LightDir To",
    type: "number",
    numeric: "float",
    min: -360,
    max: 360,
    step: 0.1,
  },
  dLightDirAnim: {
    label: "LightDir Curve",
    type: "select",
    numeric: "int",
    options: CURVE_OPTIONS,
  },
  dOffsetF: {
    label: "Offset From",
    type: "number",
    numeric: "float",
    min: -500,
    max: 500,
    step: 0.1,
  },
  dOffsetT: {
    label: "Offset To",
    type: "number",
    numeric: "float",
    min: -500,
    max: 500,
    step: 0.1,
  },
  dOffsetAnim: {
    label: "Offset Curve",
    type: "select",
    numeric: "int",
    options: CURVE_OPTIONS,
  },
  dDensityF: {
    label: "Density From",
    type: "number",
    numeric: "float",
    min: 0,
    max: 100,
    step: 0.1,
  },
  dDensityT: {
    label: "Density To",
    type: "number",
    numeric: "float",
    min: 0,
    max: 100,
    step: 0.1,
  },
  dDensityAnim: {
    label: "Density Curve",
    type: "select",
    numeric: "int",
    options: CURVE_OPTIONS,
  },
  dDiffuseF: {
    label: "Diffuse From",
    type: "number",
    numeric: "float",
    min: 0,
    max: 100,
    step: 0.1,
  },
  dDiffuseT: {
    label: "Diffuse To",
    type: "number",
    numeric: "float",
    min: 0,
    max: 100,
    step: 0.1,
  },
  dDiffuseAnim: {
    label: "Diffuse Curve",
    type: "select",
    numeric: "int",
    options: CURVE_OPTIONS,
  },
  dsType: {
    label: "Shadow Type",
    type: "select",
    numeric: "int",
    options: [
      { value: 0, label: "Soft" },
      { value: 1, label: "Hard" },
    ],
  },
  dsGrad: {
    label: "Gradient",
    type: "number",
    numeric: "float",
    min: 0,
    max: 100,
    step: 0.1,
  },
  iLightDirEna: { label: "Enable", type: "checkbox" },
  iLightDirF: {
    label: "LightDir From",
    type: "number",
    numeric: "float",
    min: -360,
    max: 360,
    step: 0.1,
  },
  iLightDirT: {
    label: "LightDir To",
    type: "number",
    numeric: "float",
    min: -360,
    max: 360,
    step: 0.1,
  },
  iLightDirAnim: {
    label: "LightDir Curve",
    type: "select",
    numeric: "int",
    options: CURVE_OPTIONS,
  },
  iOffsetF: {
    label: "Offset From",
    type: "number",
    numeric: "float",
    min: -500,
    max: 500,
    step: 0.1,
  },
  iOffsetT: {
    label: "Offset To",
    type: "number",
    numeric: "float",
    min: -500,
    max: 500,
    step: 0.1,
  },
  iOffsetAnim: {
    label: "Offset Curve",
    type: "select",
    numeric: "int",
    options: CURVE_OPTIONS,
  },
  iDensityF: {
    label: "Density From",
    type: "number",
    numeric: "float",
    min: 0,
    max: 100,
    step: 0.1,
  },
  iDensityT: {
    label: "Density To",
    type: "number",
    numeric: "float",
    min: 0,
    max: 100,
    step: 0.1,
  },
  iDensityAnim: {
    label: "Density Curve",
    type: "select",
    numeric: "int",
    options: CURVE_OPTIONS,
  },
  iDiffuseF: {
    label: "Diffuse From",
    type: "number",
    numeric: "float",
    min: 0,
    max: 100,
    step: 0.1,
  },
  iDiffuseT: {
    label: "Diffuse To",
    type: "number",
    numeric: "float",
    min: 0,
    max: 100,
    step: 0.1,
  },
  iDiffuseAnim: {
    label: "Diffuse Curve",
    type: "select",
    numeric: "int",
    options: CURVE_OPTIONS,
  },
  eLightDirEna: { label: "Enable", type: "checkbox" },
  eLightDirF: {
    label: "LightDir From",
    type: "number",
    numeric: "float",
    min: -360,
    max: 360,
    step: 0.1,
  },
  eLightDirT: {
    label: "LightDir To",
    type: "number",
    numeric: "float",
    min: -360,
    max: 360,
    step: 0.1,
  },
  eLightDirAnim: {
    label: "LightDir Curve",
    type: "select",
    numeric: "int",
    options: CURVE_OPTIONS,
  },
  eOffsetF: {
    label: "Offset From",
    type: "number",
    numeric: "float",
    min: -500,
    max: 500,
    step: 0.1,
  },
  eOffsetT: {
    label: "Offset To",
    type: "number",
    numeric: "float",
    min: -500,
    max: 500,
    step: 0.1,
  },
  eOffsetAnim: {
    label: "Offset Curve",
    type: "select",
    numeric: "int",
    options: CURVE_OPTIONS,
  },
  eDensityF: {
    label: "Density From",
    type: "number",
    numeric: "float",
    min: 0,
    max: 100,
    step: 0.1,
  },
  eDensityT: {
    label: "Density To",
    type: "number",
    numeric: "float",
    min: 0,
    max: 100,
    step: 0.1,
  },
  eDensityAnim: {
    label: "Density Curve",
    type: "select",
    numeric: "int",
    options: CURVE_OPTIONS,
  },
};

export const EFFECT_SECTIONS = [
  {
    title: "Transform",
    open: true,
    fields: [
      "antiAlias",
      "unfold",
      "animStep",
      "zoomXYSepa",
      "zoomXF",
      "zoomXT",
      "zoomXAnim",
      "zoomYF",
      "zoomYT",
      "zoomYAnim",
      "offXF",
      "offXT",
      "offXAnim",
      "offYF",
      "offYT",
      "offYAnim",
      "keepDir",
      "centerX",
      "centerY",
      "angleF",
      "angleT",
      "angleAnim",
    ],
  },
  {
    title: "Color",
    open: true,
    fields: [
      "alphaF",
      "alphaT",
      "alphaAnim",
      "brightF",
      "brightT",
      "brightAnim",
      "contrastF",
      "contrastT",
      "contrastAnim",
      "saturationF",
      "saturationT",
      "saturationAnim",
      "hueF",
      "hueT",
      "hueAnim",
    ],
  },
  {
    title: "Mask 1",
    fields: [
      "mask1Ena",
      "mask1Type",
      "mask1Grad",
      "mask1GradDir",
      "mask1StartF",
      "mask1StartT",
      "mask1StartAnim",
      "mask1StopF",
      "mask1StopT",
      "mask1StopAnim",
    ],
  },
  {
    title: "Mask 2",
    fields: [
      "mask2Ena",
      "mask2Op",
      "mask2Type",
      "mask2Grad",
      "mask2GradDir",
      "mask2StartF",
      "mask2StartT",
      "mask2StartAnim",
      "mask2StopF",
      "mask2StopT",
      "mask2StopAnim",
    ],
  },
  {
    title: "Frame Mask",
    fields: ["fMaskEna", "fMaskStart", "fMaskStop", "fMaskBits"],
  },
  {
    title: "Specular Highlight",
    fields: [
      "sLightDirF",
      "sLightDirT",
      "sLightDirAnim",
      "sDensityF",
      "sDensityT",
      "sDensityAnim",
    ],
  },
  {
    title: "Drop Shadow",
    fields: [
      "dLightDirEna",
      "dLightDirF",
      "dLightDirT",
      "dLightDirAnim",
      "dOffsetF",
      "dOffsetT",
      "dOffsetAnim",
      "dDensityF",
      "dDensityT",
      "dDensityAnim",
      "dDiffuseF",
      "dDiffuseT",
      "dDiffuseAnim",
      "dsType",
      "dsGrad",
    ],
  },
  {
    title: "Inner Shadow",
    fields: [
      "iLightDirEna",
      "iLightDirF",
      "iLightDirT",
      "iLightDirAnim",
      "iOffsetF",
      "iOffsetT",
      "iOffsetAnim",
      "iDensityF",
      "iDensityT",
      "iDensityAnim",
      "iDiffuseF",
      "iDiffuseT",
      "iDiffuseAnim",
    ],
  },
  {
    title: "Emboss",
    fields: [
      "eLightDirEna",
      "eLightDirF",
      "eLightDirT",
      "eLightDirAnim",
      "eOffsetF",
      "eOffsetT",
      "eOffsetAnim",
      "eDensityF",
      "eDensityT",
      "eDensityAnim",
    ],
  },
];
